### PR TITLE
Added progress tracking using tqdm

### PR DESCRIPTION
**Pull request by abinpaul1**
Added a progress bar to track progress of trying passwords.

### CODE REVIEW

**Comment by Sjord** [comment]
Nice. I wasn't familiar with tqdm.

It currently only shows that it's busy, and not how far it has to go, since it doens't know how many lines are in the dictionary. I thought about reading the dictionary into memory first, but I am worried that this may take up too much memory if the dictionary is large.

Would it make sense to wrap `import tqdm` in a try/except, so that the script still keeps working when tqdm is not available? Or is that overly cautious?

**Comment by abinpaul1** [comment]
Yes. Reading in the dictionary first would be a bad idea. tqdm works as a progress bar only if it knows the entire size initially.
However I came across a post here, on how to use it for large files. It calculates progress after calculating size of file initially.
[https://stackoverflow.com/questions/24890368/iterate-over-large-file-with-progress-indicator-in-python](url)
I tried adding this code and ran into another issue. The progress shown and estimated time remaining was approx correct but the number of iterations and total entries shown were very wrong. Instead of the actual 20k iterations running on my pc , it was shown as 200k.
I think we would have to decide between these two.
Either a **progress** bar  with wrong count or just raw iter count without showing progress

**Comment by Sjord** [comment]
I'll merge it like this. I briefly considered estimating the number of lines in the file, from the number of words processed so far and the current position in the file, but that gets pretty complex for something that is supposed to be simple.

**Comment by jakubboucek** [comment]
It's provide error:
```
File "jwtcrack/crackjwt.py", line 5, in <module>
    from tqdm import tqdm
```

**Comment by abinpaul1** [comment]
> It's provide error:
> 
> ```
> File "jwtcrack/crackjwt.py", line 5, in <module>
>     from tqdm import tqdm
> ```

Did you try `pip install tqdm` and then running.

**Comment by Sjord** [comment]
I added something to the README about installing tqdm.

**Pull request merged**
